services:
  - type: web
    name: uber-trip-fastapi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: guvicorn app.main:app -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:$PORT
    autoDeploy: true
